# Generated by Django 3.0.4 on 2020-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='email_city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
