# Generated by Django 3.0.4 on 2020-03-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.IntegerField(default=0)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workunit_have_cabinet', to='city.Cabinet')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workunit_have_modelprinter', to='printer.ModelPrinter')),
            ],
        ),
        migrations.AddField(
            model_name='modelprinter',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelprinter_have_producer', to='printer.Producer'),
        ),
    ]
