# Generated by Django 3.0.4 on 2020-07-05 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_cabinet'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workunit',
            old_name='name',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='workunit',
            old_name='model',
            new_name='printer',
        ),
        migrations.RemoveField(
            model_name='workunit',
            name='state',
        ),
        migrations.AddField(
            model_name='workunit',
            name='color',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workunit',
            name='staus',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='ModelCartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcartridge_have_modelprinter', to='printer.ModelPrinter')),
            ],
        ),
        migrations.CreateModel(
            name='ActPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statusPrev', models.IntegerField()),
                ('statusNext', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=255, null=True)),
                ('placementNext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actprinter_have_placementnext', to='city.Cabinet')),
                ('placementPrev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actprinter_have_placementprev', to='city.Cabinet')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actprinter_have_workunit', to='printer.WorkUnit')),
            ],
        ),
    ]
