# Generated by Django 3.0.4 on 2020-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_auto_20200705_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actprinter',
            name='placementNext',
        ),
        migrations.RemoveField(
            model_name='actprinter',
            name='placementPrev',
        ),
        migrations.RemoveField(
            model_name='actprinter',
            name='statusNext',
        ),
        migrations.RemoveField(
            model_name='actprinter',
            name='statusPrev',
        ),
        migrations.RemoveField(
            model_name='workunit',
            name='staus',
        ),
        migrations.AddField(
            model_name='actprinter',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workunit',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workunit',
            name='status_note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
