# Generated by Django 3.0.4 on 2020-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_auto_20200705_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workunit',
            name='note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='status_note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
