# Generated by Django 3.0.4 on 2020-07-06 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20200705_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actprinter',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
