# Generated by Django 3.0.4 on 2020-07-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_auto_20200706_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcartridge',
            name='printer',
        ),
        migrations.AddField(
            model_name='modelprinter',
            name='cartridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelprinter_have_modelcartridge', to='printer.ModelCartridge'),
        ),
    ]
