# Generated by Django 3.0.4 on 2020-07-28 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_auto_20200728_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='status_cartridge',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ActCartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.IntegerField(default=0)),
                ('date_finish', models.DateField(null=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actcartridge_have_modelcartridge', to='printer.ModelCartridge')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actcartridge_have_workunit', to='printer.WorkUnit')),
            ],
        ),
    ]
