# Generated by Django 3.0.4 on 2020-07-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_auto_20200728_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprinter',
            name='cartridge',
        ),
        migrations.AddField(
            model_name='modelprinter',
            name='cartridge',
            field=models.ManyToManyField(to='printer.ModelCartridge'),
        ),
    ]
