# Generated by Django 3.0.4 on 2020-08-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_modelcartridge_reserved_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actcartridge',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
