# Generated by Django 3.0.4 on 2020-03-23 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0002_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('checkout', models.BooleanField(default=False)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_have_cabinet', to='city.Cabinet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_have_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
