# Generated by Django 3.0.4 on 2020-04-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0002_auto_20200407_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comtext',
        ),
    ]
