# Generated by Django 3.0.4 on 2020-04-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0003_auto_20200420_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comtext',
            new_name='text',
        ),
    ]
