# Generated by Django 3.0.4 on 2020-04-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0004_auto_20200420_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='finishdate',
            field=models.DateField(default=None),
        ),
    ]
