# Generated by Django 3.0.4 on 2020-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0005_req_finishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='finishdate',
            field=models.DateField(blank=True),
        ),
    ]
