# Generated by Django 3.0.4 on 2020-05-25 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0006_auto_20200424_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='finishdate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
