# Generated by Django 3.0.4 on 2020-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0008_auto_20200529_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='req',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
