# Generated by Django 3.0.7 on 2020-07-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0010_auto_20200529_1321'),
        ('req', '0007_auto_20200629_1114'),
    ]

    operations = [
    ]
